theme: jekyll-theme-minimal
title: Tue Hellstern
description: Teaching at Kea
show_downloads: false

remote_theme: pages-themes/minimal@v0.2.0

github:
  is_project_page: false

plugins:
- jekyll-remote-theme
